### ISSUE TITLE
add bun support

### ISSUE THREAD

**Issue by jackbridger** [TodePond/C#2]

**Comment by TodePond** [comment]
Sorry this is the old repo. Please head to the new repo at https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite

**Comment by jackbridger** [comment]
Ok thank you, added it to the new repo. Apologies for my misunderstanding.
