### ISSUE TITLE
C LLM does not understand me disliking things

### ISSUE THREAD

**Issue by D-u-c-k-s-e-l** [TodePond/C#334]
Example prompt with chatGPT (yes I entered the setup prompt):

> User:
> 	    Run for me
> ChatGPT:
> 	    I appreciate your intention to stay active and healthy! While I can't physically run or perform exercises for you, I can certainly help provide you with exercise ideas, routines, and tips to make your workout more enjoyable. If you're interested, I can also assist you in creating a workout plan that suits your fitness goals and preferences. Let me know how you'd like to proceed!
> User:
> 	    (I don't enjoy exercising)
> ChatGPT:
>
> 	    I understand that exercising might not be enjoyable for everyone. If you're looking for alternative ways to stay active without traditional exercise, here are a few suggestions that could help you lead a more active lifestyle:
> 
> 	    Outdoor Activities: Instead of formal exercise, engage in outdoor activities you enjoy, like walking in a park, hiking, or playing a casual sport.
> 
> 	    Dancing: Put on your favorite music and dance around—it's a fun way to move your body and stay active.
> 
> 	    Household Chores: Engage in chores like gardening, cleaning, or rearranging furniture. These activities can keep you moving while also accomplishing tasks.
> 
> 	    Social Activities: Participate in social activities that involve movement, like going for a walk with friends, playing active games, or trying a new hobby.
> 
> 	    Mindful Movement: Practices like yoga, tai chi, or stretching can help you stay flexible and mobile without the intensity of traditional exercise.
> 
> 	    Active Commuting: If possible, choose to walk or bike instead of driving for short trips.
> 
> 	Remember, the key is to find activities that you genuinely enjoy and that keep you moving in a way that feels good for you. If you have specific interests, I'd be happy to help you explore ways to incorporate movement into those areas!

As I stated I do not enjoy exercise.
C LLM failed to recognize this and told me "I would if I could" (paraphrase).

**Comment by D-u-c-k-s-e-l** [comment]
#329

**Comment by TodePond** [comment]
Maybe you'd enjoy it more than you realise

**Comment by D-u-c-k-s-e-l** [comment]
ok, that explains it
